### ISSUE TITLE
ViraServers: AttributeError: 'Magic' object has no attribute 'cookie'

### ISSUE THREAD

**Issue by MaxGyver83** [n0v1c3/vira#83]
I'm using vira for the first time. When I try to connect with `:ViraServers`, I get this error message:

```
Exception ignored in: <function Magic.__del__ at 0x7fbb64189160>
```

After pressing `Ctrl-c`, I get much more output:

```
Error detected while processing function vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[35]..provider#python3#Call[18]..vira#_menu:
line   35:
Exception ignored in: <function Magic.__del__ at 0x7fbb64189160>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/magic/__init__.py", line 125, in __del__
    if self.cookie and magic_close:
AttributeError: 'Magic' object has no attribute 'cookie'

Error detected while processing function vira#_menu[92]..vira#_menu[7]..vira#_menu[35]..provider#python3#Call[18]..
vira#_menu:
line   35:
Exception ignored in: <function Magic.__del__ at 0x7fbb64189160>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/magic/__init__.py", line 125, in __del__
    if self.cookie and magic_close:
Exception ignored in: <function Magic.__del__ at 0x7fbb64189160>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/magic/__init__.py", line 125, in __del__
    if self.cookie and magic_close:
Exception ignored in: <function Magic.__del__ at 0x7fbb64189160>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/magic/__init__.py", line 125, in __del__
    if self.cookie and magic_close:
Exception ignored in: <function Magic.__del__ at 0x7fbb64189160>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/magic/__init__.py", line 125, in __del__
    if self.cookie and magic_close:
Exception ignored in: <function Magic.__del__ at 0x7fbb64189160>
-

E132: Function call depth is higher than 'maxfuncdepth'
E1098: String, List or Blob required
line   14:
E132: Function call depth is higher than 'maxfuncdepth'
E1098: String, List or Blob required
line   26:
E132: Function call depth is higher than 'maxfuncdepth'
...
```

Any ideas how to proceed?

**Comment by MaxGyver83** [comment]
> AttributeError: 'Magic' object has no attribute 'cookie'

It looks like this was a bug in `python-magic` that was fixed here: <https://github.com/ahupp/python-magic/pull/222>

After upgrading `python-magic` from version 0.4.16 to 0.4.27, I don't get this error anymore.

Now, after running `:ViraServers`, I get this output:

```
E132: Function call depth is higher than 'maxfuncdepth'
Error detected while processing function vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[9
2]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vir
a#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_men
u[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..
vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_m
enu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]
..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira
#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[
92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vi
ra#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_me
nu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92].
.vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_
menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7
]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[47]..BufEnter Autocommands for "*"..fun
ction lightline#update:
line    1:
E132: Function call depth is higher than 'maxfuncdepth'
Error detected while processing function vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[9
2]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vir
a#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_men
u[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..
vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_m
enu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]
..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira
#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[
92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vi
ra#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_me
nu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92].
.vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_
menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7
]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[47]..BufEnter Autocommands for "*"..fun
ction <SNR>63_on_bufenter:
line    1:
E132: Function call depth is higher than 'maxfuncdepth'
line   24:
E132: Function call depth is higher than 'maxfuncdepth'
Error detected while processing function vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[9
2]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vir
a#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_men
u[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..
vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_m
enu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]
..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira
#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[
92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vi
ra#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_me
nu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92].
.vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_
menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7
]..vira#_menu[92]..vira#_menu[7]..vira#_menu[92]..vira#_menu[7]..vira#_menu[47]..BufEnter Autocommands for "*"..fun
ction signature#sign#Refresh:
line    4:
E132: Function call depth is higher than 'maxfuncdepth'
line    8:
E132: Function call depth is higher than 'maxfuncdepth'
E1098: String, List or Blob required
line   14:
E132: Function call depth is higher than 'maxfuncdepth'
...
```

**Comment by MaxGyver83** [comment]
Meanwhile I can connect to the server. My `vira_servers.yaml` looks like this, now:

```yaml
https://my-company.com/trackerXX:
  token: MY_TOKEN
  skip_cert_verify: true
```

(The README says that the token is used as `password`. This didn't work.)

**Comment by mikeboiko** [comment]
Since you're using token based auth, your config should look like this:

```
https://my-company.com/trackerXX:
  username: MY_USERNAME
  password: MY_TOKEN
  skip_cert_verify: true
```

**Comment by MaxGyver83** [comment]
I think I tried this first and it didn't work. But maybe it didn't work because I tried too often in a short period. Then I found this section in the source code:

[python/Vira/vira_api.py#L212-L232](https://github.com/n0v1c3/vira/blob/master/python/Vira/vira_api.py#L212-L232)

It looks like either only the `token` or both `username` and `password` are used for authentication.

I can try again with `username` and `password` after my vacation.
